[package]
name = "raytracing_in_one_weeken"
version = "0.1.0"
authors = ["Vass Mark <Vass Mark>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.4"
termion = "1.5.6"
image = "0.23.14"
pbr = "1.0.4"